//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yogeshwarTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNote
    {
        public int NoteId { get; set; }
        public string Title { get; set; }
        public string NoteDescription { get; set; }
        public int UserId { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
